src/dependent-dropdown/accounts/urls.py
from django.urls import path
from .views import UserView, UserDetail

urlpatterns = [
    path('user/', UserView.as_view()),
    path('user/<int:pk>', UserDetail.as_view()),
]

src/dependent-dropdown/base_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, AddPerson, UpdatePerson, delete_person,PersonList, get_city_by_country_id, autocomplete

app_name = 'base_app'

urlpatterns = [
    path('', home, name="home"),
    path('add-person/', AddPerson.as_view(), name='add-person'),
    path('update-person/<int:pk>/', UpdatePerson.as_view(), name='update-person'),
    path('delete-person/<int:pk>/', delete_person, name='delete-person'),
    path('person-list/', PersonList.as_view(), name='person-list'),
    path('country-cities/<int:pk>/', get_city_by_country_id, name='country-cities'),
    path('autocomplete/', autocomplete, name='autocomplete'),
]

src/dependent-dropdown/django_root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt import views as jwt_views
from accounts.views import MyTokenObtainPairView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('base/', include('base_app.urls')),
    # path('login/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('login/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('refresh-token/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/dependent-dropdown/templates/add_person.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-3">
        <div class="col-12">
            {% if not form.instance.pk %}
            <h3 class="text-center">Add New Person</h3>
            {% else %}
            <h3 class="text-center">Update Person</h3>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center">
        <form class="col-md-8" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            {% if not form.instance.pk %}
            <button class="btn btn-outline-success btn-block">Add Person</button>
            {% else %}
            <button class="btn btn-outline-success btn-block">Update Person</button>
            {% endif %}
        </form>
    </div>
</div>
<script>
    const country = document.getElementById('id_country');
    const cities = document.getElementById('id_city');
    const host = "http://localhost:8000";
    const endpoint = "/base/country-cities/";
    country.addEventListener('change', function(event) {
        event.preventDefault();
        let selected_country_id = event.target.value;
        let url = host + endpoint;
        fetch(`${url}${selected_country_id}/`)
        .then(response=> {
            return response.json();
        })
        .then(data=> {
            let cities_html = `<option value="">------</option>`;
            for(let city of data) {
                cities_html += `<option value=${parseInt(city.id)}>${city.name}</option>`;
            }
            cities.innerHTML = cities_html;
        })
        .catch(error=> {
            console.log(error);
        })
    })
</script>
{% endblock %}

src/dependent-dropdown/templates/autocomplete.html
{% extends 'base.html' %}
{% block content %}
<form class="mt-3 d-flex m-auto" id="myForm" action="{% url 'base_app:autocomplete' %}" style="width: 50%;">
    <input class="form-control" id="personName" type="text" name="person">
    <button class="btn btn-outline-success ml-2">Submit</button>
</form>
{% endblock %}
{% block script %}
{% load static %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'js/autocomplete.js' %}"></script>
{% endblock script %}

src/dependent-dropdown/templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% include 'head.html' %}
  <body>
    <div class="container">
      <div class="row mt-3">
        <div class="col-12">
          {% if messages %}
          {% for message in messages %}
          <div
            class="alert alert-{{ message.tags }} alert-dismissible fade show"
            role="alert"
          >
            <strong class="text-monospace">{{ message }}</strong>
            <button
              type="button"
              class="close"
              data-dismiss="alert"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
    {% block content %}
    {% endblock content %}
    {% include 'script.html' %}
    {% block script %}
    {% endblock script %}
  </body>
</html>

src/dependent-dropdown/templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>

src/dependent-dropdown/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <h1 class="text-monospace">Welcome</h1>
    </div>
</div>
{% endblock %}

src/dependent-dropdown/templates/person_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row mt-3">
        <div class="col-12">
            <h3 class="text-center text-monospace">Person List</h3>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <ul class="list-group pl-0">
                {% for person in persons %}
                <li class="list-group-item text-center d-flex">
                    {{person}}
                    <a class="ml-auto btn btn-warning px-3 border text-decoration-none text-black" href="{% url 'base_app:update-person' pk=person.pk %}">Update</a>
                    <a class="ml-2 btn btn-danger px-3 border text-decoration-none text-black" href="{% url 'base_app:delete-person' pk=person.pk %}">Remove</a>
                </li>
                {% endfor %}
                <li class="list-group-item text-right">
                    <a class="btn btn-success btn-block px-3 border text-decoration-none text-black" href="{% url 'base_app:add-person' %}">Create New Entry</a>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

src/dependent-dropdown/templates/script.html
{% load static %}
<script src="{% static  'vendor/jquery/jquery.min.js'%}"></script>
<script src="{% static  'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>