src/django_authentication/authentication_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import LoginView, SignupView, LogoutView

app_name = 'authentication_app'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

src/django_authentication/django_authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication_app.views import Home
from django.contrib.auth import views as auth_views
from authentication_app.forms import EmailValidationOnResetPassword
urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication_app.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html', form_class=EmailValidationOnResetPassword), name='password_reset'),
    path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

src/django_authentication/authentication_app/models.py
from django.db import models

# Create your models here.

src/django_authentication/authentication_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class SignupForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({"class": "form-control"})
        self.fields['email'].widget.attrs.update({"class": "form-control"})
        self.fields['password1'].widget.attrs.update({"class": "form-control"})
        self.fields['password2'].widget.attrs.update({"class": "form-control"})
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean(self):
        email = self.cleaned_data['email']
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError("Username already exists")
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email already exists")
        return self.cleaned_data


class EmailValidationOnResetPassword(PasswordResetForm):
    def clean(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise ValidationError("Email does not exist in the database or user with the email is inactive")
        return self.cleaned_data

src/django_authentication/authentication_app/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views.generic import View
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import SignupForm
from .decorators import is_user_authenticated


class LoginView(View):
    @method_decorator(is_user_authenticated)
    def get(self, *args, **kwargs):
        return render(self.request, 'login.html', {})

    def post(self, *args, **kwargs):
        username = self.request.POST['username']
        password = self.request.POST['password']
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
            return redirect('home')
        else:
            messages.info(self.request, "Unauthorized Credentials")
            return redirect('authentication_app:login')


class SignupView(View):
    @method_decorator(is_user_authenticated)
    def get(self, *args, **kwargs):
        form = SignupForm()
        return render(self.request, 'signup.html', {"form": form})

    def post(self, *args, **kwargs):
        form = SignupForm(self.request.POST)
        if form.is_valid():
            form.save()
            messages.success(self.request, "Registration Successful")
            return redirect('authentication_app:login')
        return render(self.request, 'signup.html', {"form": form})


class LogoutView(View):
    def get(self, *args, **kwargs):
        logout(self.request)
        return redirect('authentication_app:login')


class Home(View):
    def get(self, *args, **kwargs):
        return render(self.request, 'home.html', {})

src/django_authentication/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Base</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <style>
      .errorlist {
        list-style: none;
        padding: 0;
      }
      .errorlist li {
        color: tomato;
      }
    </style>
  </head>
  <body>
    <div class="container">
      {% if messages %}
      {% for message in messages %}
      <div class="row justify-content-center">
        <h3 class="text-monospace text-center">{{message}}</h3>
      </div>
      {% endfor %}
      {% endif %}
    </div>
    {% block body_block %} {% endblock body_block %}
    <script>
      const inputs = document.getElementsByTagName('input');
      for(let input of inputs) {
        if(!input.classList.contains("form-control")) {
          input.classList.add("form-control");
        }
      }
    </script>
  </body>
</html>

src/django_authentication/templates/home.html
{% extends 'base.html' %}
{% block body_block %}
<h3>Home</h3>
{% if not request.user.is_authenticated %}
    <a href="{% url 'authentication_app:login' %}">Login</a>
{% else %}
<a href="{% url 'authentication_app:logout' %}">Logout</a>
{% endif %}
<a href="{% url 'authentication_app:signup' %}">Signup</a>
{% endblock body_block %}

src/django_authentication/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <form class="row my-3 justify-content-center" action="{% url 'authentication_app:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group col-md-8">
            <input class="form-control" type="text" name="username" placeholder="Enter username" required>
        </div>
        <div class="form-group col-md-8">
            <input class="form-control" type="password" name="password" placeholder="Enter password" required>
        </div>
        <div class="form-group col-md-8">
            <button type="submit" class="btn btn-success btn-block">Login</button>
        </div>
        <div class="form-group col-md-8 text-center">
            <a class="text-decoration-none text-danger" href="{% url 'password_reset' %}">Forgot Password ?</a>
        </div>
    </form>
</div>
{% endblock body_block %}

src/django_authentication/templates/password_reset.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <form class="row my-3 justify-content-center" method="POST">
        {% csrf_token %}
        {% if form.non_field_errors %}
        <div class="form-group col-md-8">
            <div class="alert alert-danger">
                {% for error in form.non_field_errors %}
                {{error}}
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <div class="form-group col-md-8">
            <label for="email">Email</label>
            {{form.email}}
        </div>
        <div class="form-group col-md-8">
            <button type="submit" class="btn btn-primary">Send email</button>
        </div>
    </form>
</div>
{% endblock body_block %}

src/django_authentication/templates/password_reset_complete.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <div class="row my-3">
        <div class="col-md-12">
            <h3>Password Rest Complete</h3>
            <p class="lead text-justify">
                Your password has been set. You may go ahead and log in now.
            </p>
            <a class="text-decoration-none" href="{% url 'authentication_app:login' %}">Log in</a>
        </div>
    </div>
</div>
{% endblock body_block %}

src/django_authentication/templates/password_reset_confirm.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <form class="row my-3 justify-content-center" method="POST">
        {% csrf_token %}
        <div class="form-group col-md-8">
            <label for="email">New Password</label>
            {{form.new_password1}}
        </div>
        <div class="form-group col-md-8">
            <label for="email">Confirm</label>
            {{form.new_password2}}
        </div>
        <div class="form-group col-md-8">
            <button type="submit" class="btn btn-primary">Reset</button>
        </div>
    </form>
</div>
{% endblock body_block %}

src/django_authentication/templates/password_reset_done.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <div class="row my-3">
        <div class="col-md-12">
            <h3>Password Rest Sent</h3>
            <p class="lead text-justify">
                We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
                
                If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
        </div>
    </div>
</div>
{% endblock body_block %}

src/django_authentication/templates/signup.html
{% extends 'base.html' %} {% block body_block %}
<div class="container">
  <form
    class="row my-3 justify-content-center"
    action="{% url 'authentication_app:signup' %}"
    method="POST"
  >
    {% csrf_token %}
    <div class="form-group col-md-8">
        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
        </div>
        {% endif %}
    </div>
    <div class="form-group col-md-8">
      <label for="username">Username</label>
      {{form.username}}
      {% if form.username.help_text %}
      {{form.username.help_text}}
      {% endif %}
      {% if form.username.errors %}
      <p>{{form.username.errors}}</p>
      {% endif %}
    </div>
    <div class="form-group col-md-8">
        <label for="username">Email</label>
        {{form.email}}
        {% if form.email.help_text %}
        {{form.email.help_text}}
        {% endif %}
        {% if form.errors.email %}
      <p>{{form.errors.email}}</p>
      {% endif %}
      </div>
      <div class="form-group col-md-8">
        <label for="password1">Password</label>
        {{form.password1}}
        {% if form.password1.help_text %}
        {{form.password1.help_text}}
        {% endif %}
        {% if form.password1.errors %}
      <p>{{form.password1.errors}}</p>
      {% endif %}
      </div>
      <div class="form-group col-md-8">
        <label for="username">Confirm Password</label>
        {{form.password2}}
        {% if form.password2.errors %}
      <p>{{form.password2.errors}}</p>
      {% endif %}
      </div>
      <div class="form-group col-md-8">
        <button type="submit" class="btn btn-outline-primary btn-block">Sign up</button>
      </div>
  </form>
</div>
<script>
  const helpText = document.querySelector('ul');
  helpText.style.padding = 0;
  helpText.style.listStyle = "none";

</script>
{% endblock body_block %}